use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Achievement {
    pub id: String,
    pub name: String,
    pub description: String,
    pub emoji: String,
    pub category: AchievementCategory,
    pub reward_xp: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum AchievementCategory {
    Levels,
    Activity,
    Dedication,
    Progression,
    Special,
    Competition,
    Content,
    Meta,
    Community,
}

impl AchievementCategory {
    pub fn title(&self) -> &str {
        match self {
            AchievementCategory::Levels => "Levels",
            AchievementCategory::Activity => "Activity",
            AchievementCategory::Dedication => "Dedication",
            AchievementCategory::Progression => "Progression",
            AchievementCategory::Special => "Special",
            AchievementCategory::Competition => "Competition",
            AchievementCategory::Content => "Content",
            AchievementCategory::Meta => "Meta",
            AchievementCategory::Community => "Community",
        }
    }
}

pub fn get_all_achievements() -> Vec<Achievement> {
    vec![
        // Level milestones
        Achievement {
            id: "first_steps".to_string(),
            name: "First Steps".to_string(),
            description: "Reach level 5".to_string(),
            emoji: "🌱".to_string(),
            category: AchievementCategory::Levels,
            reward_xp: 50,
        },
        Achievement {
            id: "rising_star".to_string(),
            name: "Rising Star".to_string(),
            description: "Reach level 10".to_string(),
            emoji: "⭐".to_string(),
            category: AchievementCategory::Levels,
            reward_xp: 100,
        },
        Achievement {
            id: "veteran".to_string(),
            name: "Veteran".to_string(),
            description: "Reach level 25".to_string(),
            emoji: "🏆".to_string(),
            category: AchievementCategory::Levels,
            reward_xp: 250,
        },
        Achievement {
            id: "legend".to_string(),
            name: "Legend".to_string(),
            description: "Reach level 50".to_string(),
            emoji: "👑".to_string(),
            category: AchievementCategory::Levels,
            reward_xp: 500,
        },
        Achievement {
            id: "centurion".to_string(),
            name: "Centurion".to_string(),
            description: "Reach level 100".to_string(),
            emoji: "💯".to_string(),
            category: AchievementCategory::Levels,
            reward_xp: 2000,
        },
        Achievement {
            id: "halfway_there".to_string(),
            name: "Halfway There".to_string(),
            description: "Reach level 15".to_string(),
            emoji: "🎯".to_string(),
            category: AchievementCategory::Levels,
            reward_xp: 150,
        },
        // Message milestones
        Achievement {
            id: "chatterbox".to_string(),
            name: "Chatterbox".to_string(),
            description: "Send 100 messages".to_string(),
            emoji: "💬".to_string(),
            category: AchievementCategory::Activity,
            reward_xp: 75,
        },
        Achievement {
            id: "conversationalist".to_string(),
            name: "Conversationalist".to_string(),
            description: "Send 500 messages".to_string(),
            emoji: "🗣️".to_string(),
            category: AchievementCategory::Activity,
            reward_xp: 150,
        },
        Achievement {
            id: "voice_of_the_server".to_string(),
            name: "Voice of the Server".to_string(),
            description: "Send 1000 messages".to_string(),
            emoji: "📢".to_string(),
            category: AchievementCategory::Activity,
            reward_xp: 300,
        },
        Achievement {
            id: "veteran_speaker".to_string(),
            name: "Veteran Speaker".to_string(),
            description: "Send 5,000 messages".to_string(),
            emoji: "🎤".to_string(),
            category: AchievementCategory::Activity,
            reward_xp: 750,
        },
        // Command usage
        Achievement {
            id: "command_novice".to_string(),
            name: "Command Novice".to_string(),
            description: "Use 25 commands".to_string(),
            emoji: "🎮".to_string(),
            category: AchievementCategory::Activity,
            reward_xp: 50,
        },
        Achievement {
            id: "command_expert".to_string(),
            name: "Command Expert".to_string(),
            description: "Use 100 commands".to_string(),
            emoji: "🕹️".to_string(),
            category: AchievementCategory::Activity,
            reward_xp: 150,
        },
        Achievement {
            id: "command_master".to_string(),
            name: "Command Master".to_string(),
            description: "Use 500 commands".to_string(),
            emoji: "🎯".to_string(),
            category: AchievementCategory::Activity,
            reward_xp: 400,
        },
        // Daily streak achievements
        Achievement {
            id: "streak_starter".to_string(),
            name: "Streak Starter".to_string(),
            description: "Maintain a 3-day daily streak".to_string(),
            emoji: "✨".to_string(),
            category: AchievementCategory::Dedication,
            reward_xp: 50,
        },
        Achievement {
            id: "week_warrior".to_string(),
            name: "Week Warrior".to_string(),
            description: "Maintain a 7-day daily streak".to_string(),
            emoji: "📅".to_string(),
            category: AchievementCategory::Dedication,
            reward_xp: 100,
        },
        Achievement {
            id: "biweekly_dedication".to_string(),
            name: "Biweekly Dedication".to_string(),
            description: "Maintain a 14-day daily streak".to_string(),
            emoji: "⚡".to_string(),
            category: AchievementCategory::Dedication,
            reward_xp: 200,
        },
        Achievement {
            id: "month_master".to_string(),
            name: "Month Master".to_string(),
            description: "Maintain a 30-day daily streak".to_string(),
            emoji: "📆".to_string(),
            category: AchievementCategory::Dedication,
            reward_xp: 500,
        },
        Achievement {
            id: "dedication_deity".to_string(),
            name: "Dedication Deity".to_string(),
            description: "Maintain a 100-day daily streak".to_string(),
            emoji: "🔥".to_string(),
            category: AchievementCategory::Dedication,
            reward_xp: 1000,
        },
        Achievement {
            id: "half_year_hero".to_string(),
            name: "Half Year Hero".to_string(),
            description: "Maintain a 180-day daily streak".to_string(),
            emoji: "🌟".to_string(),
            category: AchievementCategory::Dedication,
            reward_xp: 2500,
        },
        Achievement {
            id: "yearly_champion".to_string(),
            name: "Yearly Champion".to_string(),
            description: "Maintain a 365-day daily streak".to_string(),
            emoji: "👑".to_string(),
            category: AchievementCategory::Dedication,
            reward_xp: 5000,
        },
        // XP milestones
        Achievement {
            id: "xp_collector".to_string(),
            name: "XP Collector".to_string(),
            description: "Earn 1,000 total XP".to_string(),
            emoji: "💎".to_string(),
            category: AchievementCategory::Progression,
            reward_xp: 100,
        },
        Achievement {
            id: "xp_hoarder".to_string(),
            name: "XP Hoarder".to_string(),
            description: "Earn 5,000 total XP".to_string(),
            emoji: "💰".to_string(),
            category: AchievementCategory::Progression,
            reward_xp: 250,
        },
        Achievement {
            id: "xp_tycoon".to_string(),
            name: "XP Tycoon".to_string(),
            description: "Earn 10,000 total XP".to_string(),
            emoji: "🏰".to_string(),
            category: AchievementCategory::Progression,
            reward_xp: 500,
        },
        Achievement {
            id: "xp_millionaire".to_string(),
            name: "XP Millionaire".to_string(),
            description: "Earn 25,000 total XP".to_string(),
            emoji: "💸".to_string(),
            category: AchievementCategory::Progression,
            reward_xp: 1000,
        },
        // Special achievements
        Achievement {
            id: "early_bird".to_string(),
            name: "Early Bird".to_string(),
            description: "Claim your first daily reward".to_string(),
            emoji: "🌅".to_string(),
            category: AchievementCategory::Special,
            reward_xp: 25,
        },
        Achievement {
            id: "booster_badge".to_string(),
            name: "Booster Badge".to_string(),
            description: "Boost the server".to_string(),
            emoji: "🚀".to_string(),
            category: AchievementCategory::Special,
            reward_xp: 200,
        },
        Achievement {
            id: "server_supporter".to_string(),
            name: "Server Supporter".to_string(),
            description: "Maintain server booster status for 30 days".to_string(),
            emoji: "💖".to_string(),
            category: AchievementCategory::Special,
            reward_xp: 500,
        },
        Achievement {
            id: "well_rounded".to_string(),
            name: "Well Rounded".to_string(),
            description: "Reach level 10 with 500+ messages and 50+ commands".to_string(),
            emoji: "⚖️".to_string(),
            category: AchievementCategory::Special,
            reward_xp: 250,
        },
        // Leaderboard & Competition
        Achievement {
            id: "podium_finish".to_string(),
            name: "Podium Finish".to_string(),
            description: "Reach top 3 on the leaderboard".to_string(),
            emoji: "🥇".to_string(),
            category: AchievementCategory::Competition,
            reward_xp: 200,
        },
        Achievement {
            id: "top_ten".to_string(),
            name: "Top Ten".to_string(),
            description: "Reach top 10 on the leaderboard".to_string(),
            emoji: "🔟".to_string(),
            category: AchievementCategory::Competition,
            reward_xp: 100,
        },
        Achievement {
            id: "leaderboard_climber".to_string(),
            name: "Leaderboard Climber".to_string(),
            description: "Improve your rank by 10 positions".to_string(),
            emoji: "📈".to_string(),
            category: AchievementCategory::Competition,
            reward_xp: 150,
        },
        // Content Creator
        Achievement {
            id: "photographer".to_string(),
            name: "Photographer".to_string(),
            description: "Share 50 images in the server".to_string(),
            emoji: "📸".to_string(),
            category: AchievementCategory::Content,
            reward_xp: 100,
        },
        Achievement {
            id: "lengthy_talker".to_string(),
            name: "Lengthy Talker".to_string(),
            description: "Send 50 messages with 100+ characters".to_string(),
            emoji: "📝".to_string(),
            category: AchievementCategory::Content,
            reward_xp: 100,
        },
        Achievement {
            id: "link_sharer".to_string(),
            name: "Link Sharer".to_string(),
            description: "Share 50 links in the server".to_string(),
            emoji: "🔗".to_string(),
            category: AchievementCategory::Content,
            reward_xp: 75,
        },
        // Server Participation
        Achievement {
            id: "goal_contributor".to_string(),
            name: "Goal Contributor".to_string(),
            description: "Help complete 10 server daily goals".to_string(),
            emoji: "🎯".to_string(),
            category: AchievementCategory::Community,
            reward_xp: 200,
        },
        Achievement {
            id: "goal_enthusiast".to_string(),
            name: "Goal Enthusiast".to_string(),
            description: "Help complete 50 server daily goals".to_string(),
            emoji: "🏅".to_string(),
            category: AchievementCategory::Community,
            reward_xp: 500,
        },
        // Meta
        Achievement {
            id: "achievement_hunter".to_string(),
            name: "Achievement Hunter".to_string(),
            description: "Unlock 10 achievements".to_string(),
            emoji: "🏹".to_string(),
            category: AchievementCategory::Meta,
            reward_xp: 300,
        },
        Achievement {
            id: "completionist".to_string(),
            name: "Completionist".to_string(),
            description: "Unlock 30 achievements".to_string(),
            emoji: "💫".to_string(),
            category: AchievementCategory::Meta,
            reward_xp: 1000,
        },
    ]
}
